name: torch_light_example
description: Demonstrates how to use the torch_light plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  torch_light:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 2.3.0

flutter:
  uses-material-design: true