name: torch_light_example
description: Demonstrates how to use the torch_light plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  torch_light:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true