name: torch_light
description: A flutter plugin to control the device torch.
version: 0.4.0
homepage: https://github.com/svprdga/torch_light

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: com.svprdga.torchlight
        pluginClass: TorchLightPlugin
      ios:
        pluginClass: TorchLightPlugin
